# This is a basic workflow to help you get started with Actions

name: env

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  env:
    strategy:
      matrix:
        runner:
        - ubuntu-latest
        - ubuntu-slim
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} Env
    steps:
      - name: Env
        run: |
          : Env
          (
            echo '```'
            env | sort
            echo
            echo '```'
          ) | tee -a "$GITHUB_STEP_SUMMARY"
